# Pulling!

## GOALS

1. Identify a search term or hashtag having to do with an urban (or related) issue, problem, or application (e.g., #muralarts, #patco, #wisconsinrecount, etc.)
2. Adapt the code provided for the class examples to do the following:
<ul>
    <li>a. Extract the most recent (at most) 10,000 tweets that contain that search term/hashtag</li>
    <li>b. Clean the tweets (i.e., remove stop words, numbers, suffixes, etc.)</li>
    <li>c. Create a word cloud of the terms in the tweets</li>
    <li>d. Map the tweets</li>
<ul>

In [2]:
import geopandas as gpd
import pandas as pd
import numpy as np
from shapely.geometry import Point

import time
import requests
from datetime import datetime
import calendar

In [3]:
# UNCOMMENT TO SEE ALL ROWS/COLUMNS IN DATAFRAMES
pd.options.display.max_columns = 999
pd.options.display.max_rows = 999 
pd.options.display.max_colwidth = 200

### Keys and Such

In [4]:
bear = " "

In [ ]:
bear

## Tweepy

In [5]:
import tweepy

In [6]:
print(tweepy.__version__)

4.4.0

In [7]:
client = tweepy.Client(bearer_token=bear,  wait_on_rate_limit=True)

In [ ]:
client

In [8]:
# Search for evictions hashtag and remove retweets
query = "evictions OR evicted OR evict OR eviction -is:retweet" # remove retweets using hypen

In [ ]:
query

## Trying with geo and places

In [124]:
geo_results = []
places = {}
tweet_places = []
max_results_per_request = 50 # must be between 10 and 500

# Use the paginator to loop over all available tweets in batches of 500
# This pulls 500 tweets at a time until all tweets from the time period are pulled
for i, tweets in enumerate(
    tweepy.Paginator(
        client.search_recent_tweets,
        query=query,
        tweet_fields=["created_at", "geo"],
        place_fields=["full_name", "place_type", "geo"],
        expansions="geo.place_id",
        max_results=max_results_per_request,
        limit=1000
    )
):
    #print(f"Response #{i+1}")
    
    # Store the tweet data
    # Note: 'tweets.data' is a list of the 500 tweets
    geo_results += tweets.data
    
    # Keep track of all of the places
    try:
        for p in tweets.includes['places']:
            places[p["id"]] = p
            #places[p["geo"]] = g
            tweet_places.append(p)
            #tweet_geo.append(g)
            print(p)
            #print(g)

    except:
        
        tweet_places.append("NA")
        print("An exception occurred") 

    time.sleep(1)
print("done")

An exception occurred
Austin, TX
Brooklyn, NY
An exception occurred
An exception occurred
Pennsylvania, USA
An exception occurred
An exception occurred
An exception occurred
Guwahati, India
An exception occurred
Glasgow, Scotland
Galway, Ireland
An exception occurred
Pinellas Park, FL
An exception occurred
Pinellas Park, FL
An exception occurred
North Region, Singapore
An exception occurred
Calumet City, IL
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Silver Spring, MD
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Phoenix, AZ
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Colorado, USA
An exception occurred
An exception occurred
Sparks, NV
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Nevada, USA
An exception occurred
Phoenix, AZ
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Hayathnagar, India
An exception occurred
An exception occurred
An exception occurred
Chirala, India
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Brooklyn, NY
Tacloban City, Eastern Visayas
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Dunwoody, GA
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
East Point, GA
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Zanesville, OH
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Mandaue City, Central Visayas
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Davao City, Davao Region
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Dasmarinas, Calabarzon
Pasay City, National Capital Region
Olongapo City, Central Luzon
Salfords, South East
Tacloban City, Eastern Visayas
Central Region, Singapore
Israel
Cagayan De Oro City, Northern Mindanao
An exception occurred
An exception occurred
An exception occurred
Golborne, England
An exception occurred
An exception occurred
Rietberg, Deutschland
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Rajendra Nagar, India
An exception occurred
An exception occurred
An exception occurred
Worcester, England
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Ajman, United Arab Emirates
An exception occurred
An exception occurred
Buffalo, NY
An exception occurred
An exception occurred
An exception occurred
Hyderabad, India
An exception occurred
An exception occurred
New York, USA
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Israel
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Faversham, England
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Arkansas, USA
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Dallas, TX
Republic of the Philippines
Mandaluyong City, National Capital Region
Tanza, Calabarzon
Pittsburgh, PA
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Catalina Foothills, AZ
Andhra Pradesh, India
Dallas, TX
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Alabama, USA
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Alabama, USA
Manhattan, NY
Alabama, USA
Alabama, USA
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
West Midlands, England
An exception occurred
An exception occurred
An exception occurred
Hillsboro, OR
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Queens, NY
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Davao City, Davao Region
An exception occurred
Warsaw, Poland
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Vellakoil, India
An exception occurred
An exception occurred
Victoria, British Columbia
An exception occurred
North Auburn, CA
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred

Sablayan, Mimaropa
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Chennai, India
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Guanacaste, Costa Rica
Meath, Ireland
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Sholinganallur, India

Rate limit exceeded. Sleeping for 141 seconds.

Houston, TX
Gahanna, OH
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Louth, Ireland
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Changwon-si, Republic of Korea
An exception occurred
Waterford, Ireland
Nashville, TN
Brighton, England
An exception occurred
Hindupur, India
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Westerville, OH
Arayat, Central Luzon
An exception occurred
Kampala, Uganda
An exception occurred
An exception occurred
Cebu City, Central Visayas
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Davao City, Davao Region
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Surigao City, Caraga
An exception occurred
An exception occurred
An exception occurred
Legazpi City, Bicol Region
An exception occurred
Lubao, Central Luzon
Padre Garcia, Calabarzon
Newark, NJ
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Nairobi, Kenya
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Ottawa, Ontario
Bacoor, Calabarzon
Slough, South East
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
New York, USA
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Hojai, India
Nairobi, Kenya
An exception occurred
San Francisco, CA
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Narragansett, RI
An exception occurred
An exception occurred
An exception occurred
Kajang, Selangor
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
North Region, Singapore
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Lewisville, TX
An exception occurred
Weston-super-Mare, England
An exception occurred
An exception occurred
Cainta, Calabarzon
An exception occurred
An exception occurred
Tamil Nadu, India
An exception occurred
Sriperumbudur, India
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Tampa, FL
An exception occurred
An exception occurred
Raleigh Hills, OR
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Changwon-si, Republic of Korea
Kidapawan City, Soccsksargen
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Westminster, CA
Yorkshire and The Humber, England
An exception occurred
An exception occurred
Hasbro Children's Hospital
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Ottawa, Ontario
Kitchener, Ontario
Manchester, England
Michigan, USA
An exception occurred
An exception occurred
Buechel, KY
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Worcester, England
Pembroke, Ontario
An exception occurred
An exception occurred
An exception occurred
Higher Folds, England
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Plattsburgh, NY
Coimbatore, India
Houston, TX
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Los Angeles, CA
Ashland, OR
Drigh Road, Pakistan
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Longford, Ireland
An exception occurred
An exception occurred
Perambur Purasavakam, India
Changwon-si, Republic of Korea
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Bradford, England
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Pasay City, National Capital Region
An exception occurred
Princeton, NJ
Rhode Island, USA
An exception occurred
An exception occurred
An exception occurred
Los Angeles, CA
An exception occurred
An exception occurred
Iloilo City, Western Visayas
An exception occurred
An exception occurred
Rhode Island, USA
An exception occurred
An exception occurred
Rhode Island, USA
An exception occurred
An exception occurred
An exception occurred
Burnham, IL
Houston, TX
An exception occurred
An exception occurred
Leeds, England
Pinellas Park, FL
India
An exception occurred
An exception occurred
An exception occurred
Lilo-An, Central Visayas
An exception occurred
Wakefield, England
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Minto, Ontario
An exception occurred
An exception occurred
An exception occurred
Glasgow, Scotland
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Currimao, Ilocos Region
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Kolkata, India
An exception occurred
An exception occurred
Manchester, CT
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Rhode Island, USA
An exception occurred
An exception occurred
Colwood, British Columbia
An exception occurred
Marikina City, National Capital Region
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Kagiso, South Africa
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred

An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Queens, NY
Maine, USA
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Montréal, Québec
An exception occurred
An exception occurred
Reno, NV
Dallas, TX
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Tucson, AZ
An exception occurred
Brooklyn, NY
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Billings, MT
Pueblo Viejo, Puerto Rico
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Winchester, England
Tennessee, USA
An exception occurred
Columbus, OH
Richmond, VA
An exception occurred
Lakemoor, IL
An exception occurred
Toronto, Ontario
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Queens, NY

Rate limit exceeded. Sleeping for 296 seconds.

An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Dumfries, Scotland
Ikeja, Nigeria
An exception occurred
An exception occurred
Nashville, TN
Haveli, India
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Anekal Bangaluru, India
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Calgary, Alberta
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
New York, USA
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Johannesburg, South Africa
Denver, CO
An exception occurred
An exception occurred
West Molesey, South East
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Rae Bareily, India
An exception occurred
An exception occurred
Silchar, India
An exception occurred
An exception occurred
An exception occurred
President Roxas, Western Visayas
San Carlos City, Western Visayas
An exception occurred
An exception occurred
An exception occurred
Camberwell, London
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Kaunas, Lietuva
Dubai, United Arab Emirates
Philadelphia, PA
Pasay City, National Capital Region
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Abergavenny, Wales
An exception occurred
Bridge of Don, Scotland
An exception occurred
Woking, South East
An exception occurred
An exception occurred
An exception occurred
Impasug-Ong, Northern Mindanao
An exception occurred
An exception occurred
An exception occurred
Amloh, India
An exception occurred
Port Macquarie, New South Wales
An exception occurred
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Oshogbo, Nigeria
An exception occurred
An exception occurred
An exception occurred
An exception occurred
Cyprus
An exception occurred
Washington, DC
An exception occurred
An exception occurred
An exception occurred
done

In [125]:
# Convert to a dataframe and make a datetime column
geo_results = pd.DataFrame(geo_results)
geo_results['created_at'] = pd.to_datetime(geo_results['created_at'])

In [126]:
geo_results.head()

,created_at,geo,id,text,withheld
0,2021-12-13 04:05:36+00:00,NaN,1470243481507360768,RT @PBBabscbn: You have the power to vote for Alexa!\n\nTo VOTE VIA KUMU: Go to Kumu campaigns and choose Vote to Save or Vote to Evict a Hou…,NaN
1,2021-12-13 04:05:29+00:00,NaN,1470243453217001474,RT @thetirekinge: @lekurokami Omg! Poor baby. Imagine having the best sleep of your life only to be evicted by the landlord cause you outgr…,NaN
2,2021-12-13 04:05:11+00:00,NaN,1470243378566557698,RT @iamjavid111: Best Female Contestant In BB House RJ KAJAL Evicted👏👏Hugs and Stuffs Footage Candidates in FINALIST \n#BiggBoss5telugu,NaN
3,2021-12-13 04:04:35+00:00,NaN,1470243224685932547,"RT @Article14live: #Hindu extremists attacked his prayer service, but #Karnataka pastor Somu Avaradhi was jailed for 10 days. Landlord evic…",NaN
4,2021-12-13 04:04:17+00:00,NaN,1470243150253879297,RT @real_khabri_1: It is really sad to see makers bringing #UmarRiaz profession time &amp; again.\n\nAt least he is doing something in the house.…,NaN

In [127]:
geo_results.to_csv('geo_results.csv', index=False)

In [131]:
tweet_places.head()

                                  0
0                                NA
1  (full_name, geo, id, place_type)
2  (full_name, geo, id, place_type)
3                                NA
4                                NA

In [130]:
tweet_places = pd.DataFrame(tweet_places)
places[p["id"]] = p

In [140]:
tweet_places.to_csv('tweet_places.csv', index=False)

In [141]:
full_name=[] 

for i in range(len(tweet_places[0])):
    try:
        name=tweet_places[0][i].full_name
        full_name.append(name)
    except: 
        full_name.append("NA")

In [147]:
geo=[] 

for i in range(len(tweet_places[0])):
    try:
        n=tweet_places[0][i].geo
        geo.append(n)
    except: 
        geo.append("NA")

In [142]:
full_name

['NA',
 'Austin, TX',
 'Brooklyn, NY',
 'NA',
 'NA',
 'Pennsylvania, USA',
 'NA',
 'NA',
 'NA',
 'Guwahati, India',
 'NA',
 'Glasgow, Scotland',
 'Galway, Ireland',
 'NA',
 'Pinellas Park, FL',
 'NA',
 'Pinellas Park, FL',
 'NA',
 'North Region, Singapore',
 'NA',
 'Calumet City, IL',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Silver Spring, MD',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Phoenix, AZ',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Colorado, USA',
 'NA',
 'NA',
 'Sparks, NV',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Nevada, USA',
 'NA',
 'Phoenix, AZ',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Hayathnagar, India',
 'NA',
 'NA',
 'NA',
 'Chirala, India',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Brooklyn, NY',
 'Tacloban City, Eastern Visayas',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Dunwoody, GA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'East Point, GA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Zanesville, OH',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Mandaue City, Central Visayas',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Davao City, Davao Region',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Dasmarinas, Calabarzon',
 'Pasay City, National Capital Region',
 'Olongapo City, Central Luzon',
 'Salfords, South East',
 'Tacloban City, Eastern Visayas',
 'Central Region, Singapore',
 'Israel',
 'Cagayan De Oro City, Northern Mindanao',
 'NA',
 'NA',
 'NA',
 'Golborne, England',
 'NA',
 'NA',
 'Rietberg, Deutschland',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Rajendra Nagar, India',
 'NA',
 'NA',
 'NA',
 'Worcester, England',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Ajman, United Arab Emirates',
 'NA',
 'NA',
 'Buffalo, NY',
 'NA',
 'NA',
 'NA',
 'Hyderabad, India',
 'NA',
 'NA',
 'New York, USA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Israel',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Faversham, England',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Arkansas, USA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Dallas, TX',
 'Republic of the Philippines',
 'Mandaluyong City, National Capital Region',
 'Tanza, Calabarzon',
 'Pittsburgh, PA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Catalina Foothills, AZ',
 'Andhra Pradesh, India',
 'Dallas, TX',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Alabama, USA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Alabama, USA',
 'Manhattan, NY',
 'Alabama, USA',
 'Alabama, USA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'West Midlands, England',
 'NA',
 'NA',
 'NA',
 'Hillsboro, OR',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Queens, NY',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Davao City, Davao Region',
 'NA',
 'Warsaw, Poland',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Vellakoil, India',
 'NA',
 'NA',
 'Victoria, British Columbia',
 'NA',
 'North Auburn, CA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Sablayan, Mimaropa',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Chennai, India',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Guanacaste, Costa Rica',
 'Meath, Ireland',
 'NA',
 'NA',
 'NA',
 'NA',
 'Sholinganallur, India',
 'Houston, TX',
 'Gahanna, OH',
 'NA',
 'NA',
 'NA',
 'NA',
 'Louth, Ireland',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Changwon-si, Republic of Korea',
 'NA',
 'Waterford, Ireland',
 'Nashville, TN',
 'Brighton, England',
 'NA',
 'Hindupur, India',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Westerville, OH',
 'Arayat, Central Luzon',
 'NA',
 'Kampala, Uganda',
 'NA',
 'NA',
 'Cebu City, Central Visayas',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Davao City, Davao Region',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Surigao City, Caraga',
 'NA',
 'NA',
 'NA',
 'Legazpi City, Bicol Region',
 'NA',
 'Lubao, Central Luzon',
 'Padre Garcia, Calabarzon',
 'Newark, NJ',
 'NA',
 'NA',
 'NA',
 'NA',
 'Nairobi, Kenya',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Ottawa, Ontario',
 'Bacoor, Calabarzon',
 'Slough, South East',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'New York, USA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Hojai, India',
 'Nairobi, Kenya',
 'NA',
 'San Francisco, CA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Narragansett, RI',
 'NA',
 'NA',
 'NA',
 'Kajang, Selangor',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'North Region, Singapore',
 'NA',
 'NA',
 'NA',
 'NA',
 'Lewisville, TX',
 'NA',
 'Weston-super-Mare, England',
 'NA',
 'NA',
 'Cainta, Calabarzon',
 'NA',
 'NA',
 'Tamil Nadu, India',
 'NA',
 'Sriperumbudur, India',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Tampa, FL',
 'NA',
 'NA',
 'Raleigh Hills, OR',
 'NA',
 'NA',
 'NA',
 'NA',
 'Changwon-si, Republic of Korea',
 'Kidapawan City, Soccsksargen',
 'NA',
 'NA',
 'NA',
 'NA',
 'Westminster, CA',
 'Yorkshire and The Humber, England',
 'NA',
 'NA',
 "Hasbro Children's Hospital",
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Ottawa, Ontario',
 'Kitchener, Ontario',
 'Manchester, England',
 'Michigan, USA',
 'NA',
 'NA',
 'Buechel, KY',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Worcester, England',
 'Pembroke, Ontario',
 'NA',
 'NA',
 'NA',
 'Higher Folds, England',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Plattsburgh, NY',
 'Coimbatore, India',
 'Houston, TX',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Los Angeles, CA',
 'Ashland, OR',
 'Drigh Road, Pakistan',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Longford, Ireland',
 'NA',
 'NA',
 'Perambur Purasavakam, India',
 'Changwon-si, Republic of Korea',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Bradford, England',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Pasay City, National Capital Region',
 'NA',
 'Princeton, NJ',
 'Rhode Island, USA',
 'NA',
 'NA',
 'NA',
 'Los Angeles, CA',
 'NA',
 'NA',
 'Iloilo City, Western Visayas',
 'NA',
 'NA',
 'Rhode Island, USA',
 'NA',
 'NA',
 'Rhode Island, USA',
 'NA',
 'NA',
 'NA',
 'Burnham, IL',
 'Houston, TX',
 'NA',
 'NA',
 'Leeds, England',
 'Pinellas Park, FL',
 'India',
 'NA',
 'NA',
 'NA',
 'Lilo-An, Central Visayas',
 'NA',
 'Wakefield, England',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Minto, Ontario',
 'NA',
 'NA',
 'NA',
 'Glasgow, Scotland',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Currimao, Ilocos Region',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Kolkata, India',
 'NA',
 'NA',
 'Manchester, CT',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Rhode Island, USA',
 'NA',
 'NA',
 'Colwood, British Columbia',
 'NA',
 'Marikina City, National Capital Region',
 'NA',
 'NA',
 'NA',
 'NA',
 'Kagiso, South Africa',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Queens, NY',
 'Maine, USA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Montréal, Québec',
 'NA',
 'NA',
 'Reno, NV',
 'Dallas, TX',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Tucson, AZ',
 'NA',
 'Brooklyn, NY',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Billings, MT',
 'Pueblo Viejo, Puerto Rico',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Winchester, England',
 'Tennessee, USA',
 'NA',
 'Columbus, OH',
 'Richmond, VA',
 'NA',
 'Lakemoor, IL',
 'NA',
 'Toronto, Ontario',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Queens, NY',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Dumfries, Scotland',
 'Ikeja, Nigeria',
 'NA',
 'NA',
 'Nashville, TN',
 'Haveli, India',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Anekal Bangaluru, India',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Calgary, Alberta',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'New York, USA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Johannesburg, South Africa',
 'Denver, CO',
 'NA',
 'NA',
 'West Molesey, South East',
 'NA',
 'NA',
 'NA',
 'NA',
 'Rae Bareily, India',
 'NA',
 'NA',
 'Silchar, India',
 'NA',
 'NA',
 'NA',
 'President Roxas, Western Visayas',
 'San Carlos City, Western Visayas',
 'NA',
 'NA',
 'NA',
 'Camberwell, London',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Kaunas, Lietuva',
 'Dubai, United Arab Emirates',
 'Philadelphia, PA',
 'Pasay City, National Capital Region',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Abergavenny, Wales',
 'NA',
 'Bridge of Don, Scotland',
 'NA',
 'Woking, South East',
 'NA',
 'NA',
 'NA',
 'Impasug-Ong, Northern Mindanao',
 'NA',
 'NA',
 'NA',
 'Amloh, India',
 ...]

In [148]:
geo

['NA',
 {'type': 'Feature',
  'bbox': [-97.928935, 30.127892, -97.5805133, 30.5187994],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-74.041878, 40.570842, -73.855673, 40.739434],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-80.519851, 39.719801, -74.689517, 42.516072],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [90.939097, 25.722728, 92.180418, 26.796614],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [-4.3932845, 55.796184, -4.0902182, 55.9204214],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-10.2445252, 52.9675677, -7.9684842, 53.7190576],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [-82.752428, 27.8246325, -82.663128, 27.897396],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [-82.752428, 27.8246325, -82.663128, 27.897396],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [103.696411999967,
   1.33636499997564,
   103.866067828959,
   1.47223994098471],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [-87.579081, 41.581483, -87.525064, 41.644809],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-77.064086, 38.979735, -76.97162, 39.036964],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-112.3239143, 33.29026, -111.9254391, 33.8154652],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-109.060257, 36.992427, -102.041524, 41.003445],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-119.781386, 39.5117966, -119.640003, 39.636636],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-120.00574, 35.002086, -114.039649, 42.002208],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [-112.3239143, 33.29026, -111.9254391, 33.8154652],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [78.426176, 17.234568, 78.770343, 17.495638],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [80.1150262, 15.6170413, 80.4725874, 16.0535813],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-74.041878, 40.570842, -73.855673, 40.739434],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [124.8960325, 11.1808072, 125.0302912, 11.3431444],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-84.348046, 33.915238, -84.2649311, 33.970907],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-84.5355341, 33.609487, -84.4150479, 33.7056846],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-82.121534, 39.908312, -81.976901, 39.999527],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [123.9114563, 10.3107867, 123.9742663, 10.3998978],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [125.2148204, 6.9590062, 125.6717025, 7.6761592],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [120.9219209, 14.2623238, 121.0154811, 14.3647325],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [120.9786272, 14.5018211, 121.035272, 14.5639421],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [120.2434493, 14.8035491, 120.4370449, 14.9141509],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-0.1787389, 51.188504, -0.154345, 51.22125],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [124.8960325, 11.1808072, 125.0302912, 11.3431444],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [103.749959507073,
   1.2123138339349,
   103.918426999964,
   1.36874499902569],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [34.266924, 29.393973, 35.669933, 33.290533],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [124.4454046, 8.2312831, 124.8115962, 8.5208744],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-2.61319, 53.4623267, -2.535834, 53.487685],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [8.33321, 51.717419, 8.533875, 51.87618],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [78.233173, 17.2371055, 78.5373982, 17.5529688],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-2.2605573, 52.1631433, -2.163183, 52.226693],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [55.4228459, 24.7422387, 56.1015028, 25.4513274],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-78.912276, 42.826008, -78.79485, 42.966451],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [78.3897718, 17.3013989, 78.5404168, 17.4759],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-79.76259, 40.477383, -71.777492, 45.015851],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [34.266924, 29.393973, 35.669933, 33.290533],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [0.866301, 51.297488, 0.912072, 51.3283746],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-94.61771, 33.004106, -89.644838, 36.499767],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-96.977527, 32.620678, -96.54598, 33.019039],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [116.8748754, 4.4073918, 126.7814024, 21.1879257],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [121.0167613, 14.5674476, 121.0617602, 14.6020633],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [120.7812427, 14.2686089, 120.8755466, 14.4106597],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-80.095586, 40.3615796, -79.8657933, 40.501198],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-110.9801207, 32.250309, -110.805635, 32.355554],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [76.76081, 12.622344, 84.768782, 19.165472],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-96.977527, 32.620678, -96.54598, 33.019039],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-88.473228, 30.144425, -84.888247, 35.008029],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-88.473228, 30.144425, -84.888247, 35.008029],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-74.026675, 40.683935, -73.910408, 40.877483],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-88.473228, 30.144425, -84.888247, 35.008029],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-88.473228, 30.144425, -84.888247, 35.008029],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-3.23560072135158,
   51.8259029271059,
   -1.17213601934124,
   53.2262100153425],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-123.011705, 45.488124, -122.859355, 45.573434],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-73.962582, 40.541722, -73.699793, 40.8000371],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [125.2148204, 6.9590062, 125.6717025, 7.6761592],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [20.8525518, 52.0977088, 21.2710282, 52.3679617],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [77.698648, 10.931786, 77.725464, 10.963487],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-123.394397, 48.403014, -123.322362, 48.450447],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [-121.128403, 38.901257, -121.035533, 38.993117],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [120.7475433, 12.6370858, 121.2463724, 13.1752979],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [80.183081, 12.965942, 80.252142, 13.060495],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-87.0792369, 5.2863477, -84.7636261, 11.2168188],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-7.3440927, 53.3821295, -6.2067738, 53.9177055],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [80.056161, 12.850328, 80.268192, 13.028593],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-95.823268, 29.522325, -95.069705, 30.1546646],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-82.905845, 39.987076, -82.802554, 40.05651],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-6.6960971, 53.6985389, -6.095189, 54.1135446],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [128.369992816185,
   34.9886199520742,
   128.865006001714,
   35.3635427378255],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [-8.1621983, 51.9376708, -6.9501039, 52.3643272],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-87.022482, 35.9945681, -86.560616, 36.405448],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-0.173706, 50.80835, -0.0870057, 50.872314],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [77.4041724, 13.6833514, 77.9126739, 14.1006153],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-82.971635, 40.0804313, -82.857441, 40.217545],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [120.6464762, 15.1259977, 120.8111019, 15.2594428],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [32.4166234, 0.1648531, 32.7216969, 0.4136818],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [123.7647381, 10.2594754, 123.9287057, 10.4901895],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [125.2148204, 6.9590062, 125.6717025, 7.6761592],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [125.4232991, 9.6621152, 125.6886769, 9.9324916],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [123.6887463, 13.0319222, 123.8421512, 13.2552019],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [120.49189, 14.8099155, 120.6187795, 14.9883245],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [121.184839, 13.8535499, 121.3180256, 13.8926045],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-74.25136, 40.679997, -74.118336, 40.788991],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [36.6645733, -1.3890532, 37.0626672, -1.1606735],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-76.353876, 44.961937, -75.246407, 45.5356446],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [120.9272236, 14.3576337, 121.0117792, 14.5032792],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-0.660061, 51.4904842, -0.5251377, 51.538905],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-79.76259, 40.477383, -71.777492, 45.015851],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [92.840652, 25.990519, 92.87295, 26.024596],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [36.6645733, -1.3890532, 37.0626672, -1.1606735],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [-122.514926, 37.708075, -122.357031, 37.833238],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-71.524629, 41.358887, -71.417515, 41.503584],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [101.7180352, 2.868785, 101.8223267, 3.0293183],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [103.696411999967,
   1.33636499997564,
   103.866067828959,
   1.47223994098471],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-97.0446813, 32.985088, -96.938975, 33.0997855],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [-2.994831, 51.31404, -2.8954284, 51.3795521],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [121.094473, 14.5270254, 121.1539818, 14.6864097],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [76.233101, 8.077159, 80.346305, 13.56042],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [79.742551, 12.784445, 80.185192, 13.142529],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-82.620093, 27.821353, -82.2652945, 28.171836],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-122.772296, 45.46795, -122.74315, 45.504637],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [128.369992816185,
   34.9886199520742,
   128.865006001714,
   35.3635427378255],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [124.9639658, 6.9656884, 125.270912, 7.1195985],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-118.043083, 33.720269, -117.944373, 33.774358],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-2.56475248726412,
   53.3015341502953,
   0.149787002205902,
   54.5621550270294],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-71.40802251082259,
   41.81133122785215,
   -71.40802251082259,
   41.81133122785215],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-76.353876, 44.961937, -75.246407, 45.5356446],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-80.574116, 43.353845, -80.3786908, 43.506635],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-2.319934, 53.343623, -2.147026, 53.5702824],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-90.4181075, 41.696088, -82.122971, 48.306272],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-85.662843, 38.157856, -85.615485, 38.208355],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-2.2605573, 52.1631433, -2.163183, 52.226693],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-77.15966, 45.784298, -77.080087, 45.838653],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-2.489388, 53.499961, -2.477438, 53.508162],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-73.530573, 44.652759, -73.420227, 44.72545],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [76.657719, 10.80795, 77.100465, 11.237298],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-95.823268, 29.522325, -95.069705, 30.1546646],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-118.668404, 33.704538, -118.155409, 34.337041],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-122.736467, 42.167149, -122.6508544, 42.216145],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [67.095408, 24.868111, 67.198672, 24.899265],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-8.0366657, 53.5207471, -7.3749822, 53.9421814],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [80.1934237, 13.080055, 80.2724855, 13.1293472],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [128.369992816185,
   34.9886199520742,
   128.865006001714,
   35.3635427378255],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-1.837304, 53.773415, -1.696336, 53.858452],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [120.9786272, 14.5018211, 121.035272, 14.5639421],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [-74.710297, 40.3249504, -74.6197593, 40.3743499],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-71.907259, 41.095834, -71.088567, 42.018808],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-118.668404, 33.704538, -118.155409, 34.337041],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [122.4979499, 10.6789404, 122.6014566, 10.7798974],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-71.907259, 41.095834, -71.088567, 42.018808],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-71.907259, 41.095834, -71.088567, 42.018808],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-87.564154, 41.629452, -87.525026, 41.64654],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-95.823268, 29.522325, -95.069705, 30.1546646],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-1.706057, 53.7363694, -1.424923, 53.867543],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [-82.752428, 27.8246325, -82.663128, 27.897396],
  'properties': {}},
 {'type': 'Feature',
  'bbox': [67.997691, 6.622513, 97.170672, 37.07827],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [123.9197996, 10.3602797, 124.0229449, 10.4785882],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [-1.551536, 53.636339, -1.465554, 53.722056],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-80.991252, 43.822207, -80.74183, 44.004675],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-4.3932845, 55.796184, -4.0902182, 55.9204214],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [120.4720401, 17.9584141, 120.5277675, 18.082379],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [88.094457, 22.269493, 88.610027, 22.955918],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-72.583489, 41.733619, -72.465121, 41.820226],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-71.907259, 41.095834, -71.088567, 42.018808],
  'properties': {}},
 'NA',
 'NA',
 {'type': 'Feature',
  'bbox': [-123.518115, 48.398057, -123.442009, 48.455469],
  'properties': {}},
 'NA',
 {'type': 'Feature',
  'bbox': [121.0748367, 14.6182442, 121.1349369, 14.6756982],
  'properties': {}},
 'NA',
 'NA',
 'NA',
 'NA',
 {'type': 'Feature',

In [143]:
tweet_places3 =tweet_places[0]

In [144]:
tweet_places3

0                                     NA
1       (full_name, geo, id, place_type)
2       (full_name, geo, id, place_type)
3                                     NA
4                                     NA
                      ...
1013                                  NA
1014    (full_name, geo, id, place_type)
1015                                  NA
1016                                  NA
1017                                  NA
Name: 0, Length: 1018, dtype: object

In [145]:
tweet_places2 = pd.DataFrame(list(zip(tweet_places3,full_name)),columns =["tweet_places","full_name" ])

In [146]:
tweet_places2

                          tweet_places       full_name
0                                   NA              NA
1     (full_name, geo, id, place_type)      Austin, TX
2     (full_name, geo, id, place_type)    Brooklyn, NY
3                                   NA              NA
4                                   NA              NA
...                                ...             ...
1013                                NA              NA
1014  (full_name, geo, id, place_type)  Washington, DC
1015                                NA              NA
1016                                NA              NA
1017                                NA              NA

[1018 rows x 2 columns]

In [149]:
tweet_places2.to_csv('tweet_places2.csv', index=False)

In [139]:
tweet_places[0][1].full_name

'Austin, TX'

In [115]:
len(tweet_places)

21

In [109]:
len(geo_results)

998

In [ ]:
    try:

In [24]:
tweet_id = []
tweet_text = []
tweet_place = []
tweet_master_place = []
for tweet in tweets.data:
    print(tweet.id)
    t_id = tweet.id
    tweet_id.append(t_id)
    print(tweet.text)
    t_txt = tweet.text
    tweet_text.append(t_txt)
    try:
        if places[tweet.geo['place_id']]:
            place = places[tweet.geo['place_id']]
            print(place.full_name)
            t_pl = place.full_name
            tweet_place.append(t_pl)
            tweet_master_place.append(place)
    except: 
        print("An exception occurred")
        tweet_place.append("NA")
        tweet_master_place.append("NA")

1469994696252350465
RT @TFIAdmirer: Even though #Rjkajal Got Evicted (because of worst voting revenge by Cheeram pans) but in my view

#RJKajal - Everest
#Siri…
An exception occurred
1469994686819536900
RT @BB15LiveFeed1: Can they just evict #Ritesh #AbhijitBichukale &amp; #RajivAdatia all together in mid week?

it'll be really helpful, thanks.…
An exception occurred
1469994650794868736
RT @bloomin_style: Oh si Albie yung first ex hm na finallow ni Shai hahaha i mean given na yung kayBen since sabay silang na evict and may…
An exception occurred
1469994637540700169
RT @SundayTimesZA: A top Cape Town property developer is being assailed from all sides. He has had to leave his HQ in the Waterfront and no…
An exception occurred
1469994635300724736
RT @VeenaVasanthkmr: They clearly want to evict #pavani because they understood that she has the potential even to win but their plan is to…
An exception occurred
1469994629403590656
RT @its_dsk: You call Yourself Expert of BB..
But don't know the basics of BB.
They already Evicted 4 people in one week...so technically t…
An exception occurred
1469994603147259906
RT @dilanpcook: during a pandemic, democrats evicted people, kicked them off unemployment and made them start student loan repayment, all w…
An exception occurred
1469994526236315650
My sempathi with @ColorsTV they think Umar riaz evict 4_5 week

They never Thought Umar coming this far

Out Of syllabus questions agaya Umar riaz
They are frustrated that's why they targeted Umar riaz.hahahaa

ONE MAN SHOW UMAR
An exception occurred
1469994475703390211
"Eduction is the key to unlocking the  World".Stop forceful eviction of private schools from cantt,all over the Pakistan #saveprivateschools #saveschools_saveeducation

@PTIofficial @ChMSarwar @SaleemKhanSafi @ImranKhanPTI @JusticeGulzar @CMShehbaz @Shafqat_Mahmood https://t.co/ZtUYrq63RK
An exception occurred
1469994444229337088
RT @dilanpcook: during a pandemic, democrats evicted people, kicked them off unemployment and made them start student loan repayment, all w…
An exception occurred
1469994429108785152
RT @BB15LiveFeed1: Can they just evict #Ritesh #AbhijitBichukale &amp; #RajivAdatia all together in mid week?

it'll be really helpful, thanks.…
An exception occurred
1469994411706621954
RT @CNN: After learning that her favorite Dunkin' employee had been evicted, an Ohio woman worked with several organizations to find a new…
An exception occurred
1469994408372285442
Bigg Boss Tamil 5 Elimination 12th December 2021 Episode: Imman Annachi Gets Evicted? https://t.co/UFq1C00hSR
An exception occurred
1469994378458394628
@janjanmae1 @s10PBB 2nd Eviction palang, Evicted na dapat si Anji, so considered Saved by Sponsor na siya kahit maging Big Winner pa siya.
An exception occurred
1469994228583329793
RT @BB15LiveFeed1: Can they just evict #Ritesh #AbhijitBichukale &amp; #RajivAdatia all together in mid week?

it'll be really helpful, thanks.…
An exception occurred
1469994217984471043
RT @hautchina: ⚠️⚠️⚠️URGENT⚠️⚠️⚠️
TRANS WOMAN IN SERIOUS SHIT AND NEEDS FUNDS ASAP. SHE GOT EVICTED AND LIVES IN A SOUTHERN STATE IN AMERIK…
An exception occurred
1469994200787652608
RT @BB15LiveFeed1: Can they just evict #Ritesh #AbhijitBichukale &amp; #RajivAdatia all together in mid week?

it'll be really helpful, thanks.…
An exception occurred
1469994199260876801
Private school owners in Pindi cantonment areas protest eviction orders https://t.co/NWBpUWZasv
An exception occurred
1469994189987332096
RT @Diya_lovesBP: Mark my words #Pavni will continue to be the punchbag until she's evicted bc @vijaytelevision fixed title winner nonnan h…
An exception occurred
1469994125218836483
Jhumar very conveniently  said ke karan ne mere liye kuch nahi kiya
Well he saved him from eviction and also sacrificed his gifts for him
Ppl like jhumar are so self centered tht thy forget things acording to their convenience..
@OrmaxMedia

STOP PORTRAYING KARAN NEGATIVE
An exception occurred
1469994040632434689
RT @CNN: After learning that her favorite Dunkin' employee had been evicted, an Ohio woman worked with several organizations to find a new…
An exception occurred
1469994006696267777
@Jamesz_Zee They’re 100% going to get evicted when i don’t live here to tell them to quiet down bc families live in the building.
An exception occurred
1469993972844032002
RT @peepoye_: if @TheFarahKhan is given an option, she would evict #PratikSehalpal today itself!
Dear Farah, it's not #Pratik who's the rea…
An exception occurred
1469993934969466884
RT @TFIAdmirer: Even though #Rjkajal Got Evicted (because of worst voting revenge by Cheeram pans) but in my view

#RJKajal - Everest
#Siri…
An exception occurred
1469993930993418240
@BradleyGJ I hear ya. Got evicted with brute force by the 3 year old granddaughter from favourite chair in living room recently with a demand for a 'babychino and paw patrol'.

Haven't been that accosted since the RUC was a thing.
An exception occurred
1469993919513604098
@anthea_bailey If they don't/won't pay rent then evict them, these cosseted communists need to understand the real world. What really upsets me I'm subsidising these anarchists through my taxes.
Golborne, England
1469993907442237443
RT @its_dsk: You call Yourself Expert of BB..
But don't know the basics of BB.
They already Evicted 4 people in one week...so technically t…
An exception occurred
1469993846947782656
RT @BiggBoss_Tak: Exclusive #BiggBoss_Tak

"NO EVICTION" this weekend too.

As Voting Line were closed and Rajiv was only Safe contestant…
An exception occurred
1469993805508059140
RT @MSimath: Today save order
#Thamaraiselvi
#Akshara
#Abinay

Last 3
#Niroop
#ImmanAnnachi (Evicted)
#Amir

#biggbosstamil #Biggbosstami…
An exception occurred
1469993786512003072
RT @BB15LiveFeed1: Can they just evict #Ritesh #AbhijitBichukale &amp; #RajivAdatia all together in mid week?

it'll be really helpful, thanks.…
An exception occurred
1469993782233862144
Kapag natalo ang mga hms at walang nakuha kahit ilang percent lang ng weekly budget, kalapagin niyo yung bahay. Sa laki ng nakuha nilang pera last eviction gugutumin sila? 😂
An exception occurred
1469993692177911810
RT @djgenesisgeroni: I hope KD Estrada and Anji Salvacion will save from the 7th nomination including the 7th eviction. 🙏

Since Shanaia Go…
An exception occurred
1469993689590108166
RT @HoomanNerd: Prolly my last tweet about #Kajal coz as per leaks she is the one evicted

Appreciate her obsession with saying “Good morni…
An exception occurred
1469993675707097097
Nope eviction isn’t a game
An exception occurred
1469993606995972102
RT @riotwolfs: mazepin evicted ✅ https://t.co/CpnxMPUhkK
An exception occurred
1469993598574039041
Sana d ma evict c E mygood wla na akong masubaybayan na alliean kuya ligtas mo cla

UNITED FOR ALIEAN
An exception occurred
1469993597810339840
RT @ShubhamTharwani: Breaking News:

Because of doing personal favourisom in the show BiggBoss Evicted #FarahKhan in the middle of the show…
An exception occurred
1469993481250689029
RT @dilanpcook: during a pandemic, democrats evicted people, kicked them off unemployment and made them start student loan repayment, all w…
An exception occurred
1469993480361418753
RT @TFIAdmirer: Even though #Rjkajal Got Evicted (because of worst voting revenge by Cheeram pans) but in my view

#RJKajal - Everest
#Siri…
An exception occurred
1469993432823123970
RT @ShubhamTharwani: Breaking News:

Because of doing personal favourisom in the show BiggBoss Evicted #FarahKhan in the middle of the show…
An exception occurred
1469993429023162369
RT @Diya_lovesBP: Mark my words #Pavni will continue to be the punchbag until she's evicted bc @vijaytelevision fixed title winner nonnan h…
An exception occurred
1469993419606945798
You call Yourself Expert of BB..
But don't know the basics of BB.
They already Evicted 4 people in one week...so technically they can afford 4 weeks without removing anyone.

U should know this. https://t.co/8jKNAGXbtC
An exception occurred
1469993356814163968
RT @TheReaIKhabrri: Reason for lowest TRP

1 Giving ranks in first week
2 9 weeks only 3 captains
3 Confused creatives
4 biasedness
 5 unfa…
An exception occurred
1469993353030901765
RT @BB15LiveFeed1: Can they just evict #Ritesh #AbhijitBichukale &amp; #RajivAdatia all together in mid week?

it'll be really helpful, thanks.…
An exception occurred
1469993329056268291
RT @MIZZGW0RL: help me not get evicted and pay off the 1300 i owe my landlord that rental assistance won't cover https://t.co/G9Or0DDJ31 #M…
An exception occurred
1469993294595706881
mazepin evicted ✅ https://t.co/CpnxMPUhkK
An exception occurred
1469993277013254148
@alexeptable no she's just been evicted
An exception occurred
1469993191558598659
RT @BruckSemena: On 11/21/21, more than 2000 Tigrayans (elderly &amp; kids) were evicted from Western Tigray to Adi Goshu w/o their belongings,…
An exception occurred
1469993170767265798
RT @peepoye_: if @TheFarahKhan is given an option, she would evict #PratikSehalpal today itself!
Dear Farah, it's not #Pratik who's the rea…
An exception occurred
1469993164048322562
@Nivi5677 From the very beginning pavni used this sympathy card. I never believed her from the beginning. Her acting was more prominent when abhishek was evicted first time. Then I was more confirmed she is not trustworthy.
An exception occurred

In [25]:
df = pd.DataFrame(list(zip(tweet_id,tweet_text, tweet_place, tweet_master_place)), 
                  columns =["tweet_id","tweet_text", "tweet_place", "tweet_master_place"])

In [26]:
df.head()

,tweet_id,tweet_text,tweet_place,tweet_master_place
0,1469994696252350465,RT @TFIAdmirer: Even though #Rjkajal Got Evicted (because of worst voting revenge by Cheeram pans) but in my view\n\n#RJKajal - Everest\n#Siri…,NA,NA
1,1469994686819536900,"RT @BB15LiveFeed1: Can they just evict #Ritesh #AbhijitBichukale &amp; #RajivAdatia all together in mid week?\n\nit'll be really helpful, thanks.…",NA,NA
2,1469994650794868736,RT @bloomin_style: Oh si Albie yung first ex hm na finallow ni Shai hahaha i mean given na yung kayBen since sabay silang na evict and may…,NA,NA
3,1469994637540700169,RT @SundayTimesZA: A top Cape Town property developer is being assailed from all sides. He has had to leave his HQ in the Waterfront and no…,NA,NA
4,1469994635300724736,RT @VeenaVasanthkmr: They clearly want to evict #pavani because they understood that she has the potential even to win but their plan is to…,NA,NA

In [27]:
df["tweet_place"].unique()

array(['NA', 'Golborne, England'], dtype=object)

In [39]:
for p in tweets.includes['places']:
            #places[p["id"]] = p
            print(p)

Golborne, England

In [ ]:
# Convert to a dataframe and make a datetime column
results = pd.DataFrame(results)
results['created_at'] = pd.to_datetime(results['created_at'])

In [ ]:
len(results)

In [ ]:
results.head()

In [ ]:
results.dtypes